import { severityForScore } from "@/scoring/calculator";
import type { GeminiBand, GeminiView } from "@/report/presenters/types";

/**
 * ScoreHero evidence for the landing page (LND-7, design sprint 8 §A6 + A3.2).
 *
 * The landing ScoreHero MUST show a REAL GEO Score produced by the engine
 * (`runAudit`) against candidate URLs - never an invented number. The real
 * evidence is generated by the verification script (A3.1):
 *
 *   pnpm verify:scorehero
 *
 * which audits `scripts/scorehero-verify.test.ts` CANDIDATE_URLS and prints
 * score + band per URL. The best REAL result is copied below as a `GeminiView`
 * (the exact shape `toGeminiViewModel` produces), with its provenance.
 *
 * A3.2 (sprint 12): evidence VERIFIED on 2026-09-01 with the real script
 * against the real network. Best real candidate: moz.com - GEO Score 53
 * (poor). Category scores below are the REAL `toGeminiViewModel` output of
 * that run, copied verbatim (crawler 95, citability 36.9, E-E-A-T 54,
 * schema 60, platform 44) - schema now carries the engine's rubric score
 * (RSC-14), not the old 100 - issues*10 proxy.
 *
 * Sprint 12 dogfood baseline: the landing itself (relevy.app) audited at GEO
 * Score 47 (poor) with schema 61 (fair) - the schema row now shows the real
 * engine value, confirming the RSC-14 propagation. The ScoreHero shows the
 * best REAL candidate (moz.com), per the honesty rule (LND-7).
 */
const VERIFIED_TOTAL_SCORE = 53;
const VERIFIED_DOMAIN = "moz.com";
const VERIFIED_DATE = "2026-09-01";

export const SCOREHERO_EVIDENCE: GeminiView = {
  totalScore: VERIFIED_TOTAL_SCORE,
  // Band derived from the REAL thresholds (90/75/60/40) - never hand-written,
  // so the chip can not claim a band the score does not deserve.
  band: severityForScore(VERIFIED_TOTAL_SCORE).toLowerCase() as GeminiBand,
  domain: VERIFIED_DOMAIN,
  title: VERIFIED_DOMAIN,
  summary: `${VERIFIED_DOMAIN} - GEO Score ${VERIFIED_TOTAL_SCORE} (${severityForScore(
    VERIFIED_TOTAL_SCORE,
  ).toLowerCase()}) en ~1s`,
  durationSeconds: 1,
  // Real audit date of the verified run (A3.2) - no longer null.
  auditDate: VERIFIED_DATE,
  // Real categoryScores from `pnpm verify:scorehero` (2026-09-01) - the exact
  // `toGeminiViewModel` output for moz.com, copied verbatim.
  categoryScores: [
    {
      id: "crawler",
      name: "Acceso de bots",
      score: 95,
      maxScore: 100,
      weight: "20%",
      status: "excellent",
      keyMetric: null,
      description: "Acceso de los crawlers de IA al sitio.",
    },
    {
      id: "citability",
      name: "Citabilidad",
      score: 36.9,
      maxScore: 100,
      weight: "28%",
      status: "critical",
      keyMetric: null,
      description: "Probabilidad de que los asistentes citen los pasajes.",
    },
    {
      id: "content",
      name: "E-E-A-T",
      score: 54,
      maxScore: 100,
      weight: "24%",
      status: "poor",
      keyMetric: null,
      description: "Calidad del contenido según E-E-A-T.",
    },
    {
      id: "schema",
      name: "Datos estructurados",
      score: 60,
      maxScore: 100,
      weight: "14%",
      status: "fair",
      keyMetric: null,
      description: "Marcado de datos estructurados.",
    },
    {
      id: "platform",
      name: "Plataforma",
      score: 44,
      maxScore: 100,
      weight: "14%",
      status: "poor",
      keyMetric: null,
      description: "Preparación de la plataforma para IA.",
    },
  ],
  // The landing renders only the headline + categoryScores (page.tsx gates the
  // breakdown on categoryScores.length > 0). Findings/platforms are not
  // displayed by the landing ScoreHero, so they stay empty here - the evidence
  // contract is satisfied without fabricating rows that the UI does not show.
  findings: [],
  platforms: [],
  shareToken: null,
};
