import { severityForScore } from "@/scoring/calculator";
import type { GeminiBand, GeminiView } from "@/report/presenters/types";

/**
 * ScoreHero evidence for the landing page (LND-7, design sprint 8 §A6).
 *
 * The landing ScoreHero MUST show a REAL GEO Score produced by the engine
 * (`runAudit`) against candidate URLs — never an invented number. The real
 * evidence is generated by the verification script (A3.1):
 *
 *   pnpm verify:scorehero
 *
 * which audits `scripts/scorehero-verify.test.ts` CANDIDATE_URLS and prints
 * score + band per URL. The best REAL result is copied below as a `GeminiView`
 * (the exact shape `toGeminiViewModel` produces), with its provenance.
 *
 * TODO(A3.2): evidence PENDING — the script has not been run against the real
 * network yet (the orchestrator runs it). Replace the placeholder values below
 * with the BEST real `GeminiView` from the script output, and record here:
 *   - URL verificada
 *   - Fecha de la auditoría
 *   - Comando ejecutado (`pnpm verify:scorehero`)
 *   - GEO Score + band reales
 * Do NOT invent values: if no candidate reaches 90+, keep the best real score
 * with its honest band (e.g. 85 "good") — the UI derives band and copy from
 * this constant, so it can never overclaim "excelente" for a <90 score.
 *
 * Placeholder (unverified, pending the real run): linear.app a 85 (good).
 */
const PENDING_TOTAL_SCORE = 85;
const PENDING_DOMAIN = "linear.app";

export const SCOREHERO_EVIDENCE: GeminiView = {
  totalScore: PENDING_TOTAL_SCORE,
  // Band derived from the REAL thresholds (90/75/60/40) — never hand-written,
  // so the chip can not claim a band the score does not deserve.
  band: severityForScore(PENDING_TOTAL_SCORE).toLowerCase() as GeminiBand,
  domain: PENDING_DOMAIN,
  title: PENDING_DOMAIN,
  summary: `${PENDING_DOMAIN} — GEO Score ${PENDING_TOTAL_SCORE} (${severityForScore(
    PENDING_TOTAL_SCORE,
  ).toLowerCase()}) en ~15s`,
  durationSeconds: 15,
  auditDate: null,
  // TODO(A3.2): complete with the real category scores of the verified
  // GeminiView. Empty until then — the landing hides the breakdown rather
  // than invent dimension numbers.
  categoryScores: [],
  findings: [],
  platforms: [],
  shareToken: null,
};
